import {
  BarChart3,
  CreditCard,
  FileCheck2,
  FileText,
  FolderOpen,
  HeartHandshake,
  LayoutGrid,
  Shield,
  SlidersHorizontal,
  UserCog,
  Users,
  Waves,
} from 'lucide-vue-next'
import type { AppModule } from '../types'

export const appModules: AppModule[] = [
  {
    id: 'iptk',
    title: 'IPTK',
    description: 'Ijtimoiy-psixiatrik-tibbiy komissiya moduli uchun arizalar bilan ishlash sahifasi.',
    route: '/apps/iptk',
    icon: FileCheck2,
    enabled: true,
    permission: 'iptk.view',
    hasInternalNavigation: true,
  },
  {
    id: 'muruvvat',
    title: 'Muruvvat',
    description: 'Muruvvat moduli uchun ichki dashboard, ma’lumotlar, arizalar, internat uylari va hisobotlar skeleti.',
    route: '/apps/muruvvat',
    icon: HeartHandshake,
    enabled: true,
    permission: 'muruvvat.view',
    hasInternalNavigation: true,
  },
  {
    id: 'dashboard',
    title: 'Dashboard',
    description: 'Asosiy ko‘rsatkichlar va umumiy holat uchun tayyorlangan kirish nuqtasi.',
    route: '/apps/dashboard',
    icon: LayoutGrid,
    enabled: true,
    permission: 'dashboard.view',
  },
  {
    id: 'citizens',
    title: 'Fuqarolar reyestri',
    description: 'Reyestr, qidiruv, filtr va detal ko‘rinishlari uchun tayyor skelet.',
    route: '/apps/citizens',
    icon: Users,
    enabled: true,
    permission: 'citizens.view',
  },
  {
    id: 'applications',
    title: 'Arizalar',
    description: 'Arizalarni qabul qilish va keyingi jarayonlar uchun boshlang‘ich modul.',
    route: '/apps/applications',
    icon: FolderOpen,
    enabled: true,
    permission: 'applications.view',
  },
  {
    id: 'benefits',
    title: 'Nafaqalar',
    description: 'Nafaqa jarayonlari uchun bo‘sh, kengaytirishga tayyor sahifa.',
    route: '/apps/benefits',
    icon: Shield,
    enabled: true,
    permission: 'benefits.view',
  },
  {
    id: 'payments',
    title: 'To‘lovlar',
    description: 'Kelajakdagi to‘lov jadvallari, holatlar va integratsiyalar uchun tayyor joy.',
    route: '/apps/payments',
    icon: CreditCard,
    enabled: true,
    permission: 'payments.view',
  },
  {
    id: 'documents',
    title: 'Hujjatlar',
    description: 'Hujjatlar ro‘yxati, versiyalar va biriktirmalar uchun modul skeleti.',
    route: '/apps/documents',
    icon: FileText,
    enabled: true,
    permission: 'documents.view',
  },
  {
    id: 'monitoring',
    title: 'Monitoring',
    description: 'Jarayonlarni kuzatish va operativ nazorat uchun tayyor ko‘rinish.',
    route: '/apps/monitoring',
    icon: Waves,
    enabled: true,
    permission: 'monitoring.view',
  },
  {
    id: 'reports',
    title: 'Hisobotlar',
    description: 'Hisobotlar, eksport va analitik ko‘rinishlar uchun bo‘sh tayanch.',
    route: '/apps/reports',
    icon: BarChart3,
    enabled: true,
    permission: 'reports.view',
  },
  {
    id: 'settings',
    title: 'Sozlamalar',
    description: 'Sistemaviy sozlamalar va konfiguratsiyalar uchun tayyor modul.',
    route: '/apps/settings',
    icon: SlidersHorizontal,
    enabled: true,
    permission: 'settings.view',
  },
  {
    id: 'users',
    title: 'Foydalanuvchilar va rollar',
    description: 'RBAC va foydalanuvchi boshqaruvi uchun asosiy kirish sahifasi.',
    route: '/apps/users',
    icon: UserCog,
    enabled: true,
    permission: 'users.view',
  },
]

export function getAppModule(moduleId: string) {
  return appModules.find((module) => module.id === moduleId)
}
