<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { RouterLink } from 'vue-router'
import { ArrowLeft, ArrowRight, Check, CheckCircle2, ClipboardList, FileText, HeartHandshake, History, Phone, Plus, Send, UserRound, CalendarDays, Pencil, CircleX, PauseCircle, X } from 'lucide-vue-next'
import { usePalliativeStore } from '../store'
import { activeEpisode, ageOn, formatDate, latestAssessment, REGION_LABELS, referralErrors, SERVICE_LABELS, STATUS_LABELS } from '../domain'
import { initials, medicalIndicationLabel, nextStep, statusTone, decisionTone, stateTones, taskTone } from '../presenters'
import type { PalliativeCase } from '../types'
import type { CaseFormKind } from './PalliativeCaseForms.vue'
import PalliativeDialog from './PalliativeDialog.vue'

const props = defineProps<{ item: PalliativeCase }>()
const emit = defineEmits<{ form: [kind: CaseFormKind, taskId?: string]; feedback: [message: string, error?: boolean] }>()
const store = usePalliativeStore()
const tab = ref('overview')
const closeFamilyDialog = ref(false)
const closeError = ref('')
watch(() => props.item.id, () => { tab.value = 'overview'; closeFamilyDialog.value = false })
const tabs = [{ key: 'overview', title: 'Umumiy ma’lumot', icon: UserRound }, { key: 'referral', title: 'Baholash va yo‘llanma', icon: FileText }, { key: 'plan', title: 'Yordam rejasi', icon: HeartHandshake }, { key: 'history', title: 'Jarayon tarixi', icon: History }]
const next = computed(() => nextStep(props.item))
const papas = computed(() => latestAssessment(props.item, 'PAPAS'))
const home = computed(() => latestAssessment(props.item, 'HOME'))
const episode = computed(() => activeEpisode(props.item))
const referralIssues = computed(() => referralErrors(props.item))
const planDone = computed(() => props.item.careTasks.filter(t => t.status === 'DONE').length)
const planTotal = computed(() => props.item.careTasks.filter(t => t.status !== 'CANCELLED').length)
const cancelledPlanTasks = computed(() => props.item.careTasks.filter(t => t.status === 'CANCELLED').length)
const latestDecision = computed(() => props.item.decisions.slice(-1)[0])
const canDecide = computed(() => ['CONSILIUM', 'PAUSED', 'REJECTED', 'APPROVED'].includes(props.item.status) && props.item.referral?.status === 'SUBMITTED')
const canRefer = computed(() => !episode.value && !props.item.familySupport && props.item.status !== 'CLOSED')
function submitReferral() {
  const result = store.submitReferral(props.item.id)
  emit('feedback', result.ok ? 'Yo‘llanma Markaz konsiliumiga yuborildi.' : result.error ?? 'Yo‘llanma yuborilmadi.', !result.ok)
}
function closeFamily() {
  const result = store.closeFamilySupport(props.item.id)
  if (!result.ok) closeError.value = result.error ?? 'Yakunlanmadi.'
  else { closeFamilyDialog.value = false; emit('feedback', 'Oilaga yordam yakunlandi. Tarix saqlangan.') }
}
function advance() {
  if (props.item.status === 'CONSILIUM' || props.item.status === 'PAUSED') emit('form', 'decision')
  else if (props.item.status === 'APPROVED' && !home.value) emit('form', 'home-assessment')
  else if (props.item.status === 'FOLLOW_UP') emit('form', 'handoff')
  else if (props.item.status === 'REJECTED') emit('form', 'contact')
  else if (props.item.familySupport || episode.value) { tab.value = 'plan' }
  else if (!papas.value || props.item.status === 'OBSERVATION') emit('form', 'assessment')
  else { tab.value = 'referral' }
}
</script>

<template>
  <div class="pc-workspace space-y-5">
    <RouterLink to="/apps/palliative-care/cases" class="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ArrowLeft class="h-4 w-4" />Bolalar reyestriga qaytish</RouterLink>
    <div class="flex flex-wrap items-center gap-4 rounded-2xl border border-border bg-card p-5 sm:p-6">
      <div class="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-emerald-50 text-xl font-semibold text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200">{{ initials(item.childName) }}</div>
      <div class="min-w-0 flex-1"><p class="mb-1 text-xs font-medium tracking-wide text-muted-foreground">{{ item.number }}</p><h2 class="text-xl font-semibold sm:text-2xl">{{ item.childName }}</h2><p class="mt-1 text-sm text-muted-foreground">{{ ageOn(item.birthDate) }} yosh · {{ REGION_LABELS[item.region] }}, {{ item.district }}</p></div>
      <div class="flex flex-wrap items-center gap-3"><span :class="['rounded-full px-3 py-1.5 text-xs font-medium', statusTone(item.status)]">{{ STATUS_LABELS[item.status] }}</span><button v-if="item.status !== 'CLOSED'" class="pc-btn" aria-label="Bola ma’lumotlarini tahrirlash" @click="emit('form', 'edit')"><Pencil class="h-4 w-4" />Tahrirlash</button></div>
    </div>

    <details v-if="item.demoScenario" class="rounded-xl border border-border bg-card px-5 py-4">
      <summary class="cursor-pointer text-sm font-medium">Demo misol: {{ item.demoScenario.title }}</summary>
      <p class="mt-3 text-sm leading-6 text-muted-foreground">{{ item.demoScenario.summary }}</p>
      <ol v-if="item.demoScenario.checkpoints.length" class="mt-3 list-decimal space-y-2 pl-5 text-xs leading-5 text-muted-foreground"><li v-for="checkpoint in item.demoScenario.checkpoints" :key="checkpoint">{{ checkpoint }}</li></ol>
      <p class="mt-3 text-xs text-muted-foreground">Namunaning boshlang‘ich holati.</p>
      <RouterLink to="/apps/palliative-care/cases?view=scenarios" class="mt-3 inline-flex items-center gap-1.5 text-xs font-medium text-primary">Barcha demo misollar<ArrowRight class="h-3.5 w-3.5" /></RouterLink>
    </details>

    <div v-if="item.status !== 'CLOSED'" :class="['flex flex-col justify-between gap-4 rounded-xl border p-5 sm:flex-row sm:items-center', statusTone(item.status)]">
      <div><p class="mb-1 text-xs font-semibold uppercase tracking-wider">Keyingi qadam</p><h3 class="font-semibold">{{ next.title }}</h3><p class="mt-1 text-sm text-muted-foreground">{{ next.detail }}</p><p class="mt-2 text-xs text-muted-foreground">Mas’ul: {{ next.owner }}</p></div>
      <RouterLink v-if="next.route" :to="next.route" class="pc-btn pc-primary shrink-0">Ish oynasiga o‘tish<ArrowRight class="h-4 w-4" /></RouterLink><button v-else class="pc-btn pc-primary shrink-0" @click="advance">{{ item.status === 'REJECTED' ? 'Keyingi yordamni qayd etish' : 'Davom etish' }}<ArrowRight class="h-4 w-4" /></button>
    </div>
    <nav aria-label="Bola kartasi bo‘limlari" class="flex gap-1 overflow-x-auto border-b border-border"><button v-for="entry in tabs" :key="entry.key" :aria-current="tab === entry.key ? 'page' : undefined" :class="['flex shrink-0 items-center gap-2 border-b-2 px-4 py-3 text-sm font-medium transition', tab === entry.key ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground']" @click="tab = entry.key"><component :is="entry.icon" class="h-4 w-4" />{{ entry.title }}</button></nav>

    <div v-if="tab === 'overview'" class="grid gap-5 lg:grid-cols-3">
      <div class="space-y-5 lg:col-span-2">
        <section class="pc-panel"><h3>Bola va oila</h3><dl class="pc-definitions"><div><dt>Tug‘ilgan sana</dt><dd>{{ formatDate(item.birthDate) }}</dd></div><div><dt>Qonuniy vakil</dt><dd>{{ item.guardianName }} · {{ item.relationship }}</dd></div><div><dt>Telefon</dt><dd>{{ item.phone }}</dd></div><div><dt>Manzil</dt><dd>{{ item.address }}</dd></div><div><dt>JShShIR</dt><dd>{{ item.pinfl || 'Kiritilmagan' }}</dd></div><div><dt>Shaxs hujjati</dt><dd>{{ item.identityNumber || 'Kiritilmagan' }}</dd></div><div><dt>Oilaviy shifokor</dt><dd>{{ item.familyDoctor }}</dd></div><div><dt>Poliklinika</dt><dd>{{ item.clinic }}</dd></div></dl></section>
        <section class="pc-panel"><h3>Ehtiyoj va xizmat</h3><p class="mt-4 text-sm font-medium">{{ item.diagnosis }}</p><p class="mt-2 text-sm leading-6 text-muted-foreground">{{ item.notes || 'Qo‘shimcha murojaat mazmuni kiritilmagan.' }}</p><div v-if="item.medicalIndication" class="mt-4 rounded-lg bg-muted/60 p-3"><p class="text-xs font-medium">Tibbiy ko‘rsatma asosi</p><p class="mt-1.5 text-xs leading-5 text-muted-foreground">{{ medicalIndicationLabel(item.medicalIndication) }}</p></div><div class="mt-4 flex flex-wrap gap-2"><span v-for="symptom in item.symptoms ?? []" :key="symptom" class="rounded-md bg-muted px-2.5 py-1 text-xs">{{ symptom }}</span></div><dl class="pc-definitions mt-5"><div><dt>So‘ralgan yordam</dt><dd>{{ SERVICE_LABELS[item.requestedService] }}</dd></div><div><dt>Hozirgi xizmat</dt><dd>{{ episode ? SERVICE_LABELS[episode.service] : 'Faol epizod yo‘q' }}</dd></div><div><dt>Murojaat sanasi</dt><dd>{{ formatDate(item.intakeDate ?? item.createdAt) }}</dd></div><div><dt>Dastlabki baholash muddati</dt><dd>{{ formatDate(item.assessmentDueDate) }}</dd></div></dl></section>
        <section v-if="latestDecision" class="pc-panel"><div class="flex flex-wrap items-center justify-between gap-3"><h3>Markaz konsiliumining so‘nggi qarori</h3><button v-if="canDecide" class="text-sm font-medium text-primary" @click="emit('form', 'decision')">Qayta ko‘rib chiqish</button></div><p :class="['mt-4 inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold', decisionTone(latestDecision.outcome)]"><CheckCircle2 v-if="latestDecision.outcome === 'APPROVE'" class="h-4 w-4" /><CircleX v-else-if="latestDecision.outcome === 'REJECT'" class="h-4 w-4" /><PauseCircle v-else class="h-4 w-4" />{{ latestDecision.outcome === 'APPROVE' ? 'Qabul tasdiqlangan' : latestDecision.outcome === 'REJECT' ? 'Asosli rad etilgan' : 'Vaqtincha to‘xtatilgan' }}</p><p class="mt-3 text-sm font-medium">{{ latestDecision.number }} · {{ formatDate(latestDecision.date) }}</p><p class="mt-2 text-sm leading-6 text-muted-foreground">{{ latestDecision.reason }}</p><p class="mt-3 text-xs text-muted-foreground">{{ latestDecision.members }}</p><p v-if="latestDecision.destination" class="mt-3 rounded-lg bg-muted p-3 text-sm">Yo‘nalish: {{ latestDecision.destination }} · qayta ko‘rish: {{ formatDate(latestDecision.reviewDate) }}</p></section>
        <section v-if="item.episodes.length" class="pc-panel"><div class="flex flex-wrap items-center justify-between gap-3"><h3>Xizmat epizodlari</h3><span class="text-xs text-muted-foreground">{{ item.episodes.length }} ta epizod</span></div><article v-for="service in item.episodes.slice().reverse()" :key="service.id" class="mt-4 rounded-xl border border-border p-4"><div class="flex flex-wrap items-center justify-between gap-2"><h4 class="text-sm font-semibold">{{ SERVICE_LABELS[service.service] }}<span v-if="service.service === 'INPATIENT'" class="ml-1 font-normal text-muted-foreground">· {{ service.admissionType === 'TERMINAL' ? 'muddatsiz' : 'vaqtinchalik' }}</span></h4><span :class="['rounded-md border px-2 py-1 text-[11px]', service.status === 'ACTIVE' ? stateTones.info : stateTones.neutral]">{{ service.status === 'ACTIVE' ? 'Faol' : 'Yakunlangan' }}</span></div><p class="mt-2 text-xs text-muted-foreground">{{ formatDate(service.startDate) }} → {{ service.endDate ? formatDate(service.endDate) : service.plannedEndDate ? formatDate(service.plannedEndDate) : 'Konsilium belgilagan tartibda' }}</p><p class="mt-3 text-xs font-medium">Qabul asosi: {{ service.decisionNumber }}</p><p class="mt-1 text-sm leading-6 text-muted-foreground">{{ service.decisionReason }}</p><p v-if="service.companion" class="mt-2 text-xs text-muted-foreground">Hamroh: {{ service.companion }}</p><div v-if="service.extensions.length" class="mt-4 space-y-3 border-t border-border pt-3"><div v-for="extension in service.extensions" :key="extension.id"><p class="text-xs font-medium">Uzaytirish: {{ extension.decisionNumber }} · {{ formatDate(extension.decisionDate) }}</p><p class="mt-1 text-xs text-primary">{{ formatDate(extension.plannedEndDate) }} gacha{{ extension.adultContinuation ? ' · 18 yoshdan keyingi davom ettirish' : '' }}</p><p class="mt-1 text-xs leading-5 text-muted-foreground">{{ extension.reason }}</p></div></div><div v-if="service.closure" class="mt-4 rounded-lg bg-muted/60 p-3"><p class="text-xs font-medium">{{ service.closure.reason === 'DEATH' ? 'Vafot holati qaydi' : service.closure.reason === 'TRANSFER' ? 'Boshqa muassasaga o‘tkazish' : 'Statsionar / mobil xizmatni yakunlash' }} · {{ formatDate(service.closure.endDate) }}</p><p class="mt-2 text-sm leading-6 text-muted-foreground">{{ service.closure.summary }}</p><p class="mt-2 text-xs text-muted-foreground">Hujjat: {{ service.closure.document }}</p><p v-if="service.closure.pathologyReferral" class="mt-2 text-xs leading-5 text-muted-foreground">Vakil e’tirozi bo‘yicha yo‘nalish: {{ service.closure.pathologyReferral }}</p></div></article></section>
      </div>
      <aside class="space-y-5">
        <section class="pc-panel"><h3>Baholash natijalari</h3><div class="mt-4 grid grid-cols-2 gap-3"><div class="rounded-xl bg-muted/60 p-3"><p class="text-xs text-muted-foreground">PaPaS</p><p class="mt-2 text-3xl font-semibold">{{ papas?.score ?? '—' }}<span class="ml-1 text-xs font-normal text-muted-foreground">ball</span></p><p class="mt-2 text-xs text-muted-foreground">{{ formatDate(papas?.date) }}</p></div><div class="rounded-xl bg-muted/60 p-3"><p class="text-xs text-muted-foreground">Uyda yordam</p><p class="mt-2 text-3xl font-semibold">{{ home?.score ?? '—' }}<span class="ml-1 text-xs font-normal text-muted-foreground">ball</span></p><p class="mt-2 text-xs text-muted-foreground">{{ home ? `${home.weeklyVisits ?? home.suggestedVisits ?? '—'} tashrif / hafta` : 'Baholanmagan' }}</p></div></div><p class="mt-4 text-xs leading-5 text-muted-foreground">Natijalar shifokor xulosasidan qayd etiladi. Ikki baholash alohida yuritiladi.</p><button class="pc-btn mt-4 w-full justify-center" @click="tab = 'referral'">Baholashlarni ko‘rish<ArrowRight class="h-4 w-4" /></button></section>
        <section class="pc-panel"><h3>Individual reja</h3><p class="mt-4 text-3xl font-semibold">{{ planDone }}<span class="text-lg font-normal text-muted-foreground"> / {{ planTotal }}</span></p><p class="mt-1 text-xs text-muted-foreground">vazifa amalda bajarilgan<span v-if="cancelledPlanTasks"> · {{ cancelledPlanTasks }} ta bekor qilingan</span></p><div class="mt-4 h-2 overflow-hidden rounded-full bg-muted"><div class="h-full rounded-full bg-primary" :style="{ width: `${planTotal ? planDone / planTotal * 100 : 0}%` }" /></div><button class="pc-btn mt-4 w-full justify-center" @click="tab = 'plan'">Reja bilan ishlash<ArrowRight class="h-4 w-4" /></button></section>
        <section v-if="item.familySupport" class="pc-panel border-violet-200 dark:border-violet-900"><HeartHandshake class="h-6 w-6 text-violet-600" /><h3 class="mt-3">Oilaga keyingi yordam</h3><p class="mt-2 text-sm leading-6 text-muted-foreground">{{ item.familySupport.status === 'ACTIVE' ? 'Psixologik va ijtimoiy yordam davom etmoqda.' : 'Oilaga yordam yakunlangan.' }}</p><p class="mt-3 text-sm font-medium">{{ formatDate(item.familySupport.startDate) }} — {{ formatDate(item.familySupport.deadline) }}</p><p v-if="item.familySupport.closedAt" class="mt-2 text-xs text-muted-foreground">Yordam yakunlangan sana: {{ formatDate(item.familySupport.closedAt) }}</p><button v-if="item.familySupport.status === 'ACTIVE'" class="pc-btn mt-4" @click="tab = 'plan'">Oilaviy reja</button></section>
      </aside>
    </div>

    <div v-else-if="tab === 'referral'" class="space-y-5">
      <div class="grid gap-5 md:grid-cols-2"><section v-for="kind in (['PAPAS', 'HOME'] as const)" :key="kind" class="pc-panel"><div class="flex items-center justify-between gap-3"><h3>{{ kind === 'PAPAS' ? 'PaPaS baholashlari' : 'Uyda yordam baholashlari' }}</h3><button v-if="item.status !== 'CLOSED' && !item.familySupport" class="pc-btn" @click="emit('form', kind === 'PAPAS' ? 'assessment' : 'home-assessment')"><Plus class="h-4 w-4" />Natija kiritish</button></div><div v-for="assessment in item.assessments.filter(a => a.type === kind).slice().reverse()" :key="assessment.id" class="mt-4 rounded-lg border border-border p-4"><div class="flex items-center justify-between gap-2"><span class="text-xl font-semibold">{{ assessment.score }} <small class="text-xs font-normal">ball</small></span><span class="text-xs text-muted-foreground">{{ formatDate(assessment.date) }}</span></div><p class="mt-2 text-sm">{{ assessment.assessor }}</p><p class="mt-1 text-xs text-muted-foreground">{{ assessment.methodology }} · {{ assessment.document }}</p><p v-if="kind === 'HOME'" class="mt-3 text-sm text-primary">{{ assessment.weeklyVisits ?? assessment.suggestedVisits ?? '—' }} uy tashrifi / hafta</p><p v-if="assessment.overrideReason" class="mt-1 text-xs text-muted-foreground">Konsilium asosi: {{ assessment.overrideReason }}</p><p v-if="assessment.notes" class="mt-3 rounded-lg bg-muted/60 p-3 text-xs leading-5 text-muted-foreground">{{ assessment.notes }}</p></div><p v-if="!item.assessments.some(a => a.type === kind)" class="mt-5 py-4 text-sm text-muted-foreground">Hali baholash natijasi kiritilmagan.</p></section></div>
      <section class="pc-panel"><div class="flex flex-wrap items-center justify-between gap-3"><div><h3>Yo‘llanma va tibbiy konsilium xulosasi</h3><p class="mt-1 text-xs text-muted-foreground">Yo‘llanma beruvchi muassasa · 2-ilova</p></div><button v-if="canRefer" class="pc-btn" @click="emit('form', 'referral')"><Pencil class="h-4 w-4" />{{ item.referral ? 'Yo‘llanmani tahrirlash' : 'Yo‘llanma tayyorlash' }}</button></div>
        <dl v-if="item.referral" class="pc-definitions mt-5"><div><dt>Raqam va sana</dt><dd>{{ item.referral.number }} · {{ formatDate(item.referral.date) }}</dd></div><div><dt>Muassasa</dt><dd>{{ item.referral.organization }}</dd></div><div><dt>Konsilium xulosasi</dt><dd>{{ item.referral.sourceConsiliumNumber }} · {{ formatDate(item.referral.sourceConsiliumDate) }}</dd></div><div><dt>Muvofiqlik va XKT-10</dt><dd>{{ item.referral.sourceConsiliumEligible ? 'Tasdiqlangan' : 'Tasdiqlanmagan' }} · {{ item.referral.diagnosisCode }}</dd></div><div><dt>Yordam shakli</dt><dd>{{ SERVICE_LABELS[item.referral.service] }}</dd></div><div><dt>Kasallik tarixidan ko‘chirma</dt><dd>{{ item.referral.historyExtract || 'Kiritilmagan' }} · {{ item.referral.historyPages || 0 }} varaq</dd></div><div><dt>Tekshiruv natijalari</dt><dd>{{ item.referral.examinationDocument || 'Kiritilmagan' }} · {{ item.referral.examinationPages || 0 }} varaq</dd></div><div><dt>PaPaS hujjati</dt><dd>{{ item.referral.papasDocument || 'Kiritilmagan' }}</dd></div><div><dt>Yo‘naltiruvchi shifokor</dt><dd>{{ item.referral.referringDoctor }} · {{ item.referral.doctorPhone }}</dd></div><div><dt>Bosh shifokor / tasdiq</dt><dd>{{ item.referral.chiefDoctor }} · {{ item.referral.sourceConfirmation }}</dd></div><div><dt>Zarur jihozlar</dt><dd>{{ item.referral.requiredEquipment.join(', ') || 'Ko‘rsatilmagan' }}</dd></div><div><dt>Manba</dt><dd>{{ item.referral.source === 'PAPER' ? 'Yozma yo‘llanma' : item.referral.source === 'EPALLIATIVE' ? 'E-palliative namunasi' : 'Mahalliy prototip' }}{{ item.referral.outageReason ? ` · ${item.referral.outageReason}` : '' }}</dd></div><div class="sm:col-span-2"><dt>Marshrut va birinchi vazifalar</dt><dd>{{ item.referral.transportNotes }}</dd></div></dl>
        <div v-if="canRefer && item.referral?.status !== 'SUBMITTED'" class="mt-5 rounded-xl bg-muted/60 p-4"><p class="text-sm font-medium">Yuborishdan oldingi tekshiruv</p><ul v-if="referralIssues.length" class="mt-3 space-y-2 text-xs leading-5 text-amber-800 dark:text-amber-200"><li v-for="issue in referralIssues" :key="issue">• {{ issue }}</li></ul><p v-else class="mt-3 flex items-center gap-2 text-sm text-primary"><CheckCircle2 class="h-4 w-4" />Yo‘llanma ma’lumotlari to‘liq</p><button class="pc-btn pc-primary mt-4" @click="submitReferral"><Send class="h-4 w-4" />Markaz konsiliumiga yuborish</button></div>
        <p v-if="item.referral?.notes" class="mt-4 rounded-lg bg-muted/60 p-3 text-sm leading-6 text-muted-foreground">{{ item.referral.notes }}</p>
        <p v-if="item.referral?.status === 'SUBMITTED'" class="mt-5 flex items-center gap-2 text-sm text-primary"><CheckCircle2 class="h-4 w-4" />Markaz konsiliumiga yuborilgan · {{ formatDate(item.referral.submittedAt) }}</p>
        <button v-if="canDecide" class="pc-btn pc-primary mt-4" @click="emit('form', 'decision')"><ClipboardList class="h-4 w-4" />Markaz qarorini kiritish</button>
      </section>
    </div>

    <div v-else-if="tab === 'plan'" class="space-y-5">
      <section class="pc-panel"><div class="flex flex-wrap items-center justify-between gap-3"><div><h3>Individual yordam rejasi</h3><p class="mt-1 text-sm text-muted-foreground">{{ planDone }} / {{ planTotal }} vazifa bajarilgan{{ cancelledPlanTasks ? ` · ${cancelledPlanTasks} ta bekor qilingan` : '' }}</p></div><button v-if="item.status !== 'CLOSED'" class="pc-btn pc-primary" @click="emit('form', 'task')"><Plus class="h-4 w-4" />Vazifa qo‘shish</button></div><div v-if="!item.careTasks.length" class="py-10 text-center text-sm text-muted-foreground">Bola va oila uchun birinchi yordam vazifasini belgilang.</div><div v-for="task in item.careTasks" :key="task.id" class="mt-4 flex flex-col justify-between gap-3 rounded-xl border border-border p-4 sm:flex-row sm:items-center"><div class="flex gap-3"><span :class="['mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full', taskTone(task.status)]"><Check v-if="task.status === 'DONE'" class="h-4 w-4" /><X v-else-if="task.status === 'CANCELLED'" class="h-4 w-4" /></span><div><p class="text-sm font-medium">{{ task.title }}</p><p class="mt-1 text-xs text-muted-foreground">{{ task.assignee }} · {{ formatDate(task.dueDate) }} · {{ task.target === 'FAMILY' ? 'Oila uchun' : 'Bola uchun' }}</p><p v-if="task.cancellationNote" class="mt-2 text-xs text-muted-foreground">{{ task.cancellationNote }}</p><p v-if="task.completionNote" class="mt-2 text-sm text-muted-foreground">{{ task.completionNote }}</p></div></div><button v-if="task.status === 'PLANNED' && (!item.familySupport || task.target === 'FAMILY') && item.status !== 'CLOSED'" class="pc-btn shrink-0" @click="emit('form', 'complete-task', task.id)">Bajarilganini qayd etish</button><span v-else-if="task.status === 'DONE'" :class="['rounded-md border px-2 py-1 text-xs font-medium', stateTones.success]">Bajarilgan</span><span v-else-if="task.status === 'CANCELLED'" :class="['rounded-md border px-2 py-1 text-xs font-medium', stateTones.neutral]">Bekor qilingan</span></div></section>
      <section class="pc-panel"><div class="flex flex-wrap items-center justify-between gap-3"><h3>Muloqot va oilaviy yordam</h3><button v-if="item.status !== 'CLOSED'" class="pc-btn" @click="emit('form', 'contact')"><Phone class="h-4 w-4" />Muloqot qaydi</button></div><div v-for="contact in item.contacts.slice().reverse()" :key="contact.id" class="mt-4 border-t border-border pt-4"><p class="text-sm leading-6">{{ contact.note }}</p><p class="mt-2 text-xs text-muted-foreground">{{ contact.author }} · {{ formatDate(contact.date) }} · {{ contact.type === 'COMPLAINT' ? 'Shikoyat / murojaat' : contact.type === 'REMOTE' ? 'Masofaviy maslahat' : contact.type === 'CALL' ? 'Qo‘ng‘iroq' : 'Qayd' }}</p></div><p v-if="!item.contacts.length" class="mt-5 text-sm text-muted-foreground">Muloqotlar hali qayd etilmagan.</p></section>
      <section v-if="item.status === 'FOLLOW_UP' || item.handoffs.length" class="pc-panel"><div class="flex flex-wrap items-center justify-between gap-3"><h3>Oilaviy shifokor kuzatuvi</h3><button v-if="item.status === 'FOLLOW_UP'" class="pc-btn" @click="emit('form', 'handoff')"><CalendarDays class="h-4 w-4" />Topshirishni qayd etish</button></div><div v-for="handoff in item.handoffs" :key="handoff.id" class="mt-4 rounded-lg bg-muted/50 p-4"><p class="text-sm font-medium">{{ handoff.doctor }} · {{ handoff.clinic }}</p><p class="mt-2 text-sm">{{ handoff.note }}</p><p class="mt-2 text-xs text-muted-foreground">Topshirilgan: {{ formatDate(handoff.date) }} · {{ handoff.document }}</p><p class="mt-1 text-xs text-primary">Keyingi ko‘rik: {{ formatDate(handoff.nextReviewDate) }}</p></div></section>
      <section v-if="item.familySupport?.status === 'ACTIVE'" class="pc-panel"><h3>Oilaga yordamning davomiyligi</h3><p class="mt-3 text-sm leading-6 text-muted-foreground">Bola vafotidan keyin oilaga yordam {{ formatDate(item.familySupport.deadline) }} sanasigacha davom etishi mumkin. Yakunlashdan oldin reja va faol tashriflarni tekshiring.</p><button class="pc-btn mt-4" @click="closeError = ''; closeFamilyDialog = true">Oilaga yordamni yakunlash</button></section>
    </div>

    <section v-else class="pc-panel"><h3>Harakatlar va qarorlar tarixi</h3><ol class="mt-6"><li v-for="event in item.timeline.slice().reverse()" :key="event.id" class="relative ml-2 border-l border-border pb-7 pl-7 last:border-transparent last:pb-0"><span class="absolute -left-[5px] top-1 h-2.5 w-2.5 rounded-full bg-primary ring-4 ring-card" /><p class="text-xs text-muted-foreground">{{ formatDate(event.at) }} · {{ event.actor }}</p><p class="mt-1.5 text-sm font-semibold">{{ event.title }}</p><p class="mt-1 text-sm leading-6 text-muted-foreground">{{ event.detail }}</p></li></ol></section>
    <PalliativeDialog :open="closeFamilyDialog" title="Oilaga yordamni yakunlash" description="Faol yordam yakunlanadi. Bajarilmagan oilaviy vazifalar va tashriflar bekor qilingan deb qayd etiladi; barcha xizmatlar tarixi saqlanadi." @close="closeFamilyDialog = false"><p v-if="closeError" role="alert" class="mb-4 text-sm text-rose-700">{{ closeError }}</p><div class="flex justify-end gap-3"><button :class="['pc-btn', stateTones.neutral]" @click="closeFamilyDialog = false"><X class="h-4 w-4" />Bekor qilish</button><button class="pc-btn !bg-slate-700 !text-white hover:!bg-slate-800" @click="closeFamily"><Check class="h-4 w-4" />Yakunlashni tasdiqlash</button></div></PalliativeDialog>
  </div>
</template>

<style scoped>
.pc-panel { padding: 22px; border: 1px solid var(--border); border-radius: 14px; background: var(--card); }
.pc-panel h3 { font-size: 15px; font-weight: 600; }
.pc-btn { display: inline-flex; align-items: center; justify-content: center; gap: 8px; border: 1px solid var(--border); border-radius: 8px; padding: 9px 13px; font-size: 13px; font-weight: 500; background: var(--card); }
.pc-btn:hover { background: var(--muted); }
.pc-btn:focus-visible { outline: 2px solid var(--primary); outline-offset: 3px; }
.pc-primary { background: var(--primary); color: var(--primary-foreground); border-color: var(--primary); }
.pc-primary:hover { background: var(--primary-hover); }
.pc-definitions { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: 20px; margin-top: 20px; }
.pc-definitions dt { font-size: 12px; color: var(--muted-foreground); margin-bottom: 5px; }
.pc-definitions dd { font-size: 13px; line-height: 1.7; overflow-wrap: anywhere; }
@media(max-width: 500px) { .pc-definitions { grid-template-columns: 1fr; gap: 15px; } .pc-panel { padding: 17px; } }
</style>
