import type {
  AppealStatus,
  CasePhase,
  IntakeChannelCode,
  PlanStatus,
  PTPKCase,
  PTPKCaseTypeDefinition,
  PTPKProcessStep,
  PTPKReferenceDefinition,
  PTPKServiceRouteDefinition,
  PTPKStatusDefinition,
  ReferralStatus,
} from './types'

export const ptpkCaseTypeDefinitions: PTPKCaseTypeDefinition[] = [
  {
    code: 'C1',
    title: 'Yangi yoki xizmatga jalb etilmagan bola',
    description: 'Bola ilgari ta’lim yoki tegishli xizmatlar tizimida bo‘lmagan birlamchi murojaat.',
    routeHint: 'STANDARD',
    firstAction: 'Shaxsni aniqlash, dublikatni tekshirish va dastlabki triage.',
  },
  {
    code: 'C2',
    title: 'Yangi qondirilmagan ehtiyoj',
    description: 'Bola bir xizmatni olayapti, lekin boshqa yo‘nalishda yangi ehtiyoj aniqlandi.',
    routeHint: 'STANDARD',
    firstAction: 'Mavjud xizmatlarni saqlagan holda yangi ehtiyojni baholash.',
  },
  {
    code: 'C3',
    title: 'Qayta jalb qilish',
    description: 'Ta’lim yoki xizmatdan uzilib qolgan bolani qayta jalb etish holati.',
    routeHint: 'STANDARD',
    firstAction: 'Uzilish sababini va xavfsiz qayta kirish yo‘lini aniqlash.',
  },
  {
    code: 'C4',
    title: 'Rejali qayta ko‘rib chiqish',
    description: 'Rejada belgilangan muddat yetgani sabab ehtiyoj va natijalarni qayta baholash.',
    routeHint: 'REVIEW',
    firstAction: 'Reja natijalari va amaldagi xizmatlarning samaradorligini tekshirish.',
  },
  {
    code: 'C5',
    title: 'Hodisa asosidagi qayta baholash',
    description: 'Sog‘liq, oila, xavfsizlik yoki funksional holat o‘zgarishi sababli qayta baholash.',
    routeHint: 'REVIEW',
    firstAction: 'Hodisaning ta’sirini triage qilish va reja versiyasini ochish.',
  },
  {
    code: 'C6',
    title: 'O‘tish yoki ko‘chirish',
    description: 'Bog‘chadan maktabga, bosqichlar yoki hududlar o‘rtasida uzluksiz o‘tish.',
    routeHint: 'STANDARD',
    firstAction: 'Qabul qiluvchi tashkilot, quvvat va uzluksizlik rejasini kelishish.',
  },
  {
    code: 'C7',
    title: 'Shoshilinch sog‘liq yoki himoya holati',
    description: 'Bolaning hayoti, sog‘lig‘i yoki xavfsizligiga zudlik bilan javob talab qiluvchi signal.',
    routeHint: 'URGENT',
    firstAction: 'Vaqtinchalik xavfsiz xizmatni darhol ishga tushirish va inson qarorini jalb etish.',
  },
  {
    code: 'C8',
    title: 'Tasdiqlangan xizmat ko‘rsatilmagan',
    description: 'Ehtiyoj va xizmat tasdiqlangan, ammo quvvat, provayder yoki kirish to‘sig‘i sabab boshlanmagan.',
    routeHint: 'DELIVERY_FAILURE',
    firstAction: 'Ehtiyojni bekor qilmasdan to‘siqni eskalatsiya va muqobil provayderni qidirish.',
  },
  {
    code: 'C9',
    title: 'Qayta ko‘rib chiqish yoki apellyatsiya',
    description: 'Oila yoki vakil qarorni qayta ko‘rib chiqishni so‘ragan holat.',
    routeHint: 'APPEAL',
    firstAction: 'Apellyatsiyani mustaqil oqimda ro‘yxatga olish va xavfsiz xizmatlarni davom ettirish.',
  },
]

export const ptpkServiceRouteDefinitions: PTPKServiceRouteDefinition[] = [
  {
    code: 'S0',
    title: 'Bazaviy yordam va monitoring',
    description: 'Maxsus yo‘llanmasiz ko‘rsatiladigan universal yordam hamda dinamik kuzatuv.',
    examples: ['Ota-onaga yo‘l-yo‘riq', 'Maktabdagi bazaviy moslashtirish', 'Rejali monitoring'],
    color: '#64748b',
  },
  {
    code: 'S1',
    title: 'Ta’lim',
    description: 'Maktabgacha, maktab, uyda yoki boshqa moslashtirilgan ta’lim shakli.',
    examples: ['Inklyuziv sinf', 'Resurs pedagog', 'Uyda ta’lim'],
    color: '#2563eb',
  },
  {
    code: 'S2',
    title: 'Erta aralashuv va rivojlantirish',
    description: 'Rivojlanishning ilk davrida bolaga va oilaga ko‘rsatiladigan xizmatlar.',
    examples: ['Logoped', 'Ergoterapiya', 'Rivojlantiruvchi mashg‘ulot'],
    color: '#7c3aed',
  },
  {
    code: 'S3',
    title: 'Tibbiy va reabilitatsiya',
    description: 'Tibbiy kuzatuv, davolash, reabilitatsiya va yordamchi vositalar.',
    examples: ['Reabilitatsiya kursi', 'Texnik vosita', 'Mutaxassis konsultatsiyasi'],
    color: '#0891b2',
  },
  {
    code: 'S4',
    title: 'Ijtimoiy xizmatlar',
    description: 'Uyda, kunduzgi yoki mahallada ko‘rsatiladigan ijtimoiy parvarish va qo‘llab-quvvatlash.',
    examples: ['Kunduzgi parvarish', 'Uyda xizmat', 'Ijtimoiy hamrohlik'],
    color: '#059669',
  },
  {
    code: 'S5',
    title: 'Oila, kirish va himoya',
    description: 'Oilani qo‘llab-quvvatlash, transport, kirish to‘siqlari va bolaning himoyasi.',
    examples: ['Transport', 'Oila konsultatsiyasi', 'Himoya rejasi'],
    color: '#d97706',
  },
  {
    code: 'S6',
    title: 'Integratsiyalashgan paket',
    description: 'Bir nechta tizimning kelishilgan maqsad va muddatlarda taqdim etadigan kompleks paketi.',
    examples: ['O‘tish davri paketi', 'Ko‘p tarmoqli intensiv yordam', 'Yagona case-manager'],
    color: '#db2777',
  },
]

export const ptpkIntakeChannelDefinitions: PTPKReferenceDefinition<IntakeChannelCode>[] = [
  { code: 'FAMILY', title: 'Oila yoki bolaning murojaati', description: 'Ota-ona, vakil yoki bolaning bevosita murojaati.' },
  { code: 'EDUCATION', title: 'Ta’lim tashkiloti', description: 'Bog‘cha, maktab yoki boshqa ta’lim tashkiloti signali.' },
  { code: 'HEALTHCARE', title: 'Sog‘liqni saqlash', description: 'Poliklinika, shifoxona yoki reabilitatsiya tashkiloti signali.' },
  { code: 'SOCIAL_SERVICE', title: 'Ijtimoiy xizmat', description: 'Ijtimoiy xodim yoki xizmat ko‘rsatuvchi markaz signali.' },
  { code: 'MAHALLA', title: 'Mahalla', description: 'Mahalla yettiligi yoki hududiy aniqlash orqali kelgan signal.' },
  { code: 'CHILD_PROTECTION', title: 'Bola himoyasi', description: 'Himoya, huquqni muhofaza qilish yoki xavfsizlik kanali.' },
  { code: 'PROVIDER', title: 'Xizmat ko‘rsatuvchi', description: 'Amaldagi xizmat provayderi yuborgan yangi ehtiyoj yoki ijro signali.' },
  { code: 'SYSTEM_EVENT', title: 'Tizim hodisasi', description: 'Muddat, uzilish, kutish yoki integratsiya hodisasi orqali avtomatik signal.' },
]

export const ptpkCasePhaseDefinitions: PTPKStatusDefinition<CasePhase>[] = [
  { code: 'SIGNAL_RECEIVED', title: 'Signal qabul qilindi', tone: 'info' },
  { code: 'IDENTITY_CHECK', title: 'Shaxs va dublikat tekshiruvi', tone: 'info' },
  { code: 'TRIAGE', title: 'Triage', tone: 'warning' },
  { code: 'ASSESSMENT', title: 'Funksional baholash', tone: 'purple' },
  { code: 'PLAN_DEVELOPMENT', title: 'Reja tuzilmoqda', tone: 'purple' },
  { code: 'AUTHORIZATION', title: 'Tasdiqlash', tone: 'warning' },
  { code: 'SERVICE_COORDINATION', title: 'Xizmatlarni muvofiqlashtirish', tone: 'info' },
  { code: 'MONITORING', title: 'Ijro monitoringi', tone: 'success' },
  { code: 'REVIEW', title: 'Qayta ko‘rib chiqish', tone: 'warning' },
  { code: 'CLOSED', title: 'Yopilgan', tone: 'neutral' },
]

export const ptpkPlanStatusDefinitions: PTPKStatusDefinition<PlanStatus>[] = [
  { code: 'NOT_STARTED', title: 'Boshlanmagan', tone: 'neutral' },
  { code: 'DRAFT', title: 'Qoralama', tone: 'info' },
  { code: 'FAMILY_REVIEW', title: 'Oila ko‘rib chiqmoqda', tone: 'purple' },
  { code: 'APPROVAL_PENDING', title: 'Tasdiq kutilmoqda', tone: 'warning' },
  { code: 'APPROVED', title: 'Tasdiqlangan', tone: 'success' },
  { code: 'ACTIVE', title: 'Amalda', tone: 'success' },
  { code: 'REVISION_REQUIRED', title: 'Yangilash talab etiladi', tone: 'warning' },
  { code: 'COMPLETED', title: 'Yakunlangan', tone: 'neutral' },
  { code: 'CANCELLED', title: 'Bekor qilingan', tone: 'danger' },
]

export const ptpkReferralStatusDefinitions: PTPKStatusDefinition<ReferralStatus>[] = [
  { code: 'DRAFT', title: 'Qoralama', tone: 'neutral' },
  { code: 'READY_TO_REFER', title: 'Yo‘llashga tayyor', tone: 'info' },
  { code: 'REFERRED', title: 'Yo‘llangan', tone: 'info' },
  { code: 'MATCHING', title: 'Provayder qidirilmoqda', tone: 'purple' },
  { code: 'WAITLISTED', title: 'Kutish ro‘yxatida', tone: 'warning' },
  { code: 'PROVIDER_ACCEPTED', title: 'Provayder qabul qildi', tone: 'success' },
  { code: 'PROVIDER_DECLINED', title: 'Provayder qabul qilmadi', tone: 'danger' },
  { code: 'SCHEDULED', title: 'Boshlanish sanasi belgilangan', tone: 'success' },
  { code: 'STARTED', title: 'Xizmat boshlandi', tone: 'success' },
  { code: 'PAUSED', title: 'Vaqtincha to‘xtagan', tone: 'warning' },
  { code: 'COMPLETED', title: 'Xizmat yakunlangan', tone: 'neutral' },
  { code: 'CANCELLED', title: 'Bekor qilingan', tone: 'danger' },
]

export const ptpkAppealStatusDefinitions: PTPKStatusDefinition<AppealStatus>[] = [
  { code: 'NONE', title: 'Apellyatsiya yo‘q', tone: 'neutral' },
  { code: 'SUBMITTED', title: 'Qabul qilindi', tone: 'info' },
  { code: 'ADMISSIBILITY_CHECK', title: 'Dastlabki tekshiruv', tone: 'warning' },
  { code: 'UNDER_REVIEW', title: 'Ko‘rib chiqilmoqda', tone: 'purple' },
  { code: 'DECISION_MADE', title: 'Qaror chiqarildi', tone: 'success' },
  { code: 'IMPLEMENTATION_PENDING', title: 'Qaror ijrosi kutilmoqda', tone: 'warning' },
  { code: 'IMPLEMENTED', title: 'Qaror ijro etildi', tone: 'success' },
  { code: 'WITHDRAWN', title: 'Qaytarib olindi', tone: 'neutral' },
  { code: 'CLOSED', title: 'Yopilgan', tone: 'neutral' },
]

export const ptpkProcessSteps: PTPKProcessStep[] = [
  {
    order: 1,
    key: 'signal',
    title: 'Signal va yagona case',
    description: 'Sakkiz kanaldan kelgan signal bola profili va mavjud case’lar bilan bog‘lanadi.',
    automatedChecks: ['PINFL yoki demografik moslik', 'Dublikat case', 'Mavjud xizmatlar'],
    humanDecision: 'Noaniq shaxs yoki takroriy murojaatni birlashtirish.',
  },
  {
    order: 2,
    key: 'legal-basis',
    title: 'Rozilik yoki huquqiy asos',
    description: 'Ma’lumot almashish uchun rozilik yoki qonuniy asos qayd etiladi.',
    automatedChecks: ['Rozilikning amal muddati', 'Vakil vakolati'],
    humanDecision: 'Rozilik talab qilinmaydigan himoya holatini tasdiqlash.',
  },
  {
    order: 3,
    key: 'triage',
    title: 'Triage va yo‘lni tanlash',
    description: 'Standart, shoshilinch, ijrodagi uzilish yoki apellyatsiya oqimi tanlanadi.',
    automatedChecks: ['Risk indikatorlari', 'SLA', 'C1–C9 tavsiyasi'],
    humanDecision: 'Shoshilinchlik va yuqori ta’sirli yo‘nalish qarori.',
  },
  {
    order: 4,
    key: 'assessment',
    title: 'Maqsadli funksional baholash',
    description: 'Faqat qaror uchun zarur domenlar bo‘yicha baholash o‘tkaziladi.',
    automatedChecks: ['Yetishmayotgan domenlar', 'Avvalgi baholashning dolzarbligi'],
    humanDecision: 'Bolaning individual konteksti va oilaning fikrini talqin qilish.',
  },
  {
    order: 5,
    key: 'plan',
    title: 'Integratsiyalashgan reja',
    description: 'Maqsad, xizmat, mas’ul, muddat va qayta ko‘rib chiqish sanasi bir rejada jamlanadi.',
    automatedChecks: ['Reja to‘liqligi', 'Xizmatlar o‘rtasidagi ziddiyat'],
    humanDecision: 'Oila va bola bilan rejaning maqsadga muvofiqligini kelishish.',
  },
  {
    order: 6,
    key: 'authorization',
    title: 'Tasdiqlash',
    description: 'Yuqori ta’sirli qarorlar izoh va dalillar bilan vakolatli shaxs tomonidan tasdiqlanadi.',
    automatedChecks: ['Vakolat', 'Siyosat versiyasi', 'Majburiy dalillar'],
    humanDecision: 'Tasdiqlash, qayta ishlashga yuborish yoki asoslangan rad qarori.',
  },
  {
    order: 7,
    key: 'referrals',
    title: 'Parallel yo‘llanmalar',
    description: 'S0–S6 xizmatlari bir-birini kutmasdan alohida statuslarda yuradi.',
    automatedChecks: ['Provayder quvvati', 'Hudud va kirish imkoniyati', 'Takroriy yo‘llanma'],
    humanDecision: 'Provayder va muqobil xizmatni tanlash.',
  },
  {
    order: 8,
    key: 'delivery',
    title: 'Xizmatning amalda boshlanishi',
    description: 'Yo‘llanma berilgani emas, provayder tasdiqlagan amaldagi boshlanish qayd etiladi.',
    automatedChecks: ['Boshlanish tasdig‘i', 'Kutish muddati', 'C8 signali'],
    humanDecision: 'Kechikishda eskalatsiya yoki muqobil provayderga o‘tkazish.',
  },
  {
    order: 9,
    key: 'monitoring',
    title: 'Monitoring va qayta ko‘rib chiqish',
    description: 'Natija, qatnashuv, uzilish va yangi ehtiyojlar doimiy kuzatiladi.',
    automatedChecks: ['Review sanasi', 'Uzilish hodisasi', 'Natija indikatorlari'],
    humanDecision: 'Rejani yangilash, davom ettirish yoki xavfsiz yopish.',
  },
]

export const ptpkBusinessRules = [
  'Avtomatik tavsiya yuqori ta’sirli rad yoki cheklov qarorini chiqarmaydi.',
  'Provayder quvvati yo‘qligi bolaning ehtiyoji yo‘q degani emas; yo‘llanma WAITLISTED holatida qoladi.',
  'Bitta reja ichida bir nechta S0–S6 yo‘llanmasi parallel va mustaqil statuslarda yurishi mumkin.',
  'Apellyatsiya, qayta ko‘rib chiqish yoki ko‘chirish xavfsiz amaldagi xizmatlarni avtomatik to‘xtatmaydi.',
  'Case faqat yo‘llanma berilgani uchun yopilmaydi; zarur xizmatlar amalda boshlangani yoki asoslangan yakun qayd etiladi.',
  'Yetishmayotgan hujjat, integratsiya xatosi yoki kutish ro‘yxati case’ni yopish sababi bo‘la olmaydi.',
  'Case, reja, har bir yo‘llanma va apellyatsiya o‘z state-machine’i bilan yuradi.',
  'Xizmat turlari, mezonlar va qaror siyosatlari kod hamda amal sanasi bilan versiyalanadi.',
]

export const ptpkDemoCases: PTPKCase[] = [
  {
    id: 'case-001',
    displayId: 'PTPK-2026-00142',
    type: 'C1',
    intakeChannel: 'FAMILY',
    priority: 'PRIORITY',
    phase: 'ASSESSMENT',
    child: {
      id: 'child-001',
      fullName: 'Muhammadali Karimov',
      birthDate: '2020-04-16',
      pinfl: '52004160000001',
      gender: 'MALE',
      district: 'Yunusobod tumani',
      representativeName: 'Nilufar Karimova',
      representativePhone: '+998 90 000 01 01',
      educationEngagement: 'NOT_ENGAGED',
    },
    signalSummary: 'Bola hali maktabgacha ta’limga jalb etilmagan, nutq va muloqotda qo‘llab-quvvatlash zarur.',
    needs: [
      { id: 'need-001-a', domain: 'COMMUNICATION', summary: 'Ekspressiv nutq va kundalik muloqot', severity: 'HIGH', assessed: true },
      { id: 'need-001-b', domain: 'LEARNING', summary: 'Ta’lim muhitiga bosqichma-bosqich moslashish', severity: 'MEDIUM', assessed: false },
    ],
    consentStatus: 'RECORDED',
    assignedTeam: 'Yunusobod tuman multidisiplinar jamoasi',
    owner: 'M. Saidova',
    createdAt: '2026-08-26T09:20:00+05:00',
    updatedAt: '2026-08-29T10:15:00+05:00',
    dueAt: '2026-09-03',
    nextAction: 'Ta’lim va kommunikatsiya baholashini yakunlash',
    flags: { urgent: false, safeguarding: false, currentlyUnserved: true, overdue: false },
    plan: {
      id: 'plan-001',
      version: 1,
      status: 'DRAFT',
      goals: ['Kundalik ehtiyojlarini ifodalash', 'Mos ta’lim muhitiga xavfsiz kirish'],
      owner: 'M. Saidova',
      referrals: [
        { id: 'ref-001-a', serviceCode: 'S1', serviceName: 'Inklyuziv maktabgacha ta’lim', status: 'DRAFT', owner: 'D. Akramov', requestedAt: '2026-08-29', updatedAt: '2026-08-29T10:15:00+05:00' },
        { id: 'ref-001-b', serviceCode: 'S2', serviceName: 'Logoped va erta aralashuv', status: 'READY_TO_REFER', owner: 'N. Xasanova', requestedAt: '2026-08-29', targetStartDate: '2026-09-08', updatedAt: '2026-08-29T10:10:00+05:00' },
      ],
    },
    timeline: [
      { id: 'evt-001-a', at: '2026-08-26T09:20:00+05:00', kind: 'SIGNAL', title: 'Oila murojaati qabul qilindi', description: 'Birlamchi case avtomatik dublikat tekshiruvidan o‘tdi.', actor: 'Yagona portal' },
      { id: 'evt-001-b', at: '2026-08-28T14:10:00+05:00', kind: 'ASSESSMENT', title: 'Kommunikatsiya baholandi', description: 'Maqsadli funksional baholash natijasi qayd etildi.', actor: 'N. Xasanova' },
    ],
  },
  {
    id: 'case-002',
    displayId: 'PTPK-2026-00137',
    type: 'C2',
    intakeChannel: 'PROVIDER',
    priority: 'PRIORITY',
    phase: 'SERVICE_COORDINATION',
    child: {
      id: 'child-002',
      fullName: 'Malika Abduvaliyeva',
      birthDate: '2016-11-03',
      pinfl: '41611030000002',
      gender: 'FEMALE',
      district: 'Chilonzor tumani',
      representativeName: 'Dilorom Abduvaliyeva',
      representativePhone: '+998 90 000 01 02',
      educationEngagement: 'SCHOOL',
    },
    signalSummary: 'Inklyuziv ta’lim davom etmoqda, harakatlanishdagi o‘zgarish sabab yangi reabilitatsiya ehtiyoji aniqlandi.',
    needs: [
      { id: 'need-002-a', domain: 'MOBILITY', summary: 'Harakatlanish va maktabga xavfsiz yetib borish', severity: 'HIGH', assessed: true },
      { id: 'need-002-b', domain: 'LEARNING', summary: 'Amaldagi inklyuziv ta’limni davom ettirish', severity: 'MEDIUM', assessed: true },
    ],
    consentStatus: 'RECORDED',
    assignedTeam: 'Chilonzor tuman multidisiplinar jamoasi',
    owner: 'O. Ergashev',
    createdAt: '2026-08-21T11:40:00+05:00',
    updatedAt: '2026-08-29T09:40:00+05:00',
    dueAt: '2026-08-31',
    nextAction: 'Muqobil reabilitatsiya provayderini tasdiqlash',
    flags: { urgent: false, safeguarding: false, currentlyUnserved: false, overdue: false },
    plan: {
      id: 'plan-002',
      version: 2,
      status: 'ACTIVE',
      goals: ['Ta’limni uzmaslik', 'Mustaqil harakatlanish imkonini yaxshilash'],
      familyReviewedAt: '2026-08-23',
      approvedAt: '2026-08-24',
      reviewDate: '2026-10-01',
      owner: 'O. Ergashev',
      referrals: [
        { id: 'ref-002-a', serviceCode: 'S1', serviceName: 'Inklyuziv ta’lim va resurs pedagog', status: 'STARTED', providerName: '214-sonli maktab', owner: 'G. Tursunova', requestedAt: '2026-01-12', actualStartDate: '2026-01-20', updatedAt: '2026-08-27T16:00:00+05:00' },
        { id: 'ref-002-b', serviceCode: 'S3', serviceName: 'Harakat reabilitatsiyasi', status: 'WAITLISTED', providerName: 'Shahar reabilitatsiya markazi', owner: 'S. Umarov', requestedAt: '2026-08-24', targetStartDate: '2026-09-02', waitingDays: 5, capacityNote: 'Sentyabr guruhi uchun navbat', updatedAt: '2026-08-29T09:40:00+05:00' },
        { id: 'ref-002-c', serviceCode: 'S5', serviceName: 'Maktab transporti', status: 'MATCHING', owner: 'D. Rahimov', requestedAt: '2026-08-25', targetStartDate: '2026-09-01', updatedAt: '2026-08-29T08:30:00+05:00' },
      ],
    },
    timeline: [
      { id: 'evt-002-a', at: '2026-08-21T11:40:00+05:00', kind: 'SIGNAL', title: 'Provayder yangi ehtiyojni bildirdi', description: 'Mavjud case yopilmasdan yangi reja versiyasi ochildi.', actor: '214-sonli maktab' },
      { id: 'evt-002-b', at: '2026-08-29T09:40:00+05:00', kind: 'REFERRAL', title: 'Reabilitatsiya navbatga qo‘yildi', description: 'Ehtiyoj saqlandi, muqobil provayder qidiruvi boshlandi.', actor: 'S. Umarov' },
    ],
  },
  {
    id: 'case-003',
    displayId: 'PTPK-2026-00131',
    type: 'C3',
    intakeChannel: 'EDUCATION',
    priority: 'PRIORITY',
    phase: 'PLAN_DEVELOPMENT',
    child: {
      id: 'child-003',
      fullName: 'Asadbek Qodirov',
      birthDate: '2014-02-21',
      pinfl: '41402210000003',
      gender: 'MALE',
      district: 'Olmazor tumani',
      representativeName: 'Zuhra Qodirova',
      representativePhone: '+998 90 000 01 03',
      educationEngagement: 'NOT_ENGAGED',
    },
    signalSummary: 'Oilaviy ko‘chishdan keyin uch oy davomida maktab va ijtimoiy xizmatlardan uzilgan.',
    needs: [
      { id: 'need-003-a', domain: 'LEARNING', summary: 'Maktabga qayta jalb qilish', severity: 'HIGH', assessed: true },
      { id: 'need-003-b', domain: 'FAMILY_ACCESS', summary: 'Ro‘yxatdan o‘tish va transport to‘sig‘ini bartaraf etish', severity: 'MEDIUM', assessed: true },
    ],
    consentStatus: 'RECORDED',
    assignedTeam: 'Olmazor tuman multidisiplinar jamoasi',
    owner: 'L. Botirova',
    createdAt: '2026-08-20T08:50:00+05:00',
    updatedAt: '2026-08-28T17:20:00+05:00',
    dueAt: '2026-09-02',
    nextAction: 'Oila bilan qayta jalb qilish rejasini kelishish',
    flags: { urgent: false, safeguarding: false, currentlyUnserved: true, overdue: false },
    plan: {
      id: 'plan-003',
      version: 1,
      status: 'FAMILY_REVIEW',
      goals: ['Maktabga uzluksiz qaytish', 'Oilaga kirish to‘siqlarini hal qilish'],
      reviewDate: '2026-09-30',
      owner: 'L. Botirova',
      referrals: [
        { id: 'ref-003-a', serviceCode: 'S1', serviceName: 'Hududiy maktabga qayta qabul', status: 'PROVIDER_ACCEPTED', providerName: '298-sonli maktab', owner: 'A. Jalilov', requestedAt: '2026-08-24', targetStartDate: '2026-09-02', updatedAt: '2026-08-28T15:00:00+05:00' },
        { id: 'ref-003-b', serviceCode: 'S4', serviceName: 'Ijtimoiy hamrohlik', status: 'REFERRED', providerName: 'Inson markazi', owner: 'N. Yo‘ldosheva', requestedAt: '2026-08-25', updatedAt: '2026-08-28T17:20:00+05:00' },
      ],
    },
    timeline: [
      { id: 'evt-003-a', at: '2026-08-20T08:50:00+05:00', kind: 'SIGNAL', title: 'Davomat uzilishi aniqlandi', description: 'Ta’lim tizimi C3 signalini yubordi.', actor: 'Ta’lim integratsiyasi' },
      { id: 'evt-003-b', at: '2026-08-28T15:00:00+05:00', kind: 'REFERRAL', title: 'Maktab joyni tasdiqladi', description: 'Qayta jalb qilish sanasi oilaga taklif etildi.', actor: 'A. Jalilov' },
    ],
  },
  {
    id: 'case-004',
    displayId: 'PTPK-2026-00088',
    type: 'C4',
    intakeChannel: 'SYSTEM_EVENT',
    priority: 'ROUTINE',
    phase: 'REVIEW',
    child: {
      id: 'child-004',
      fullName: 'Muslima Hamroyeva',
      birthDate: '2021-07-09',
      pinfl: '62107090000004',
      gender: 'FEMALE',
      district: 'Mirzo Ulug‘bek tumani',
      representativeName: 'Feruza Hamroyeva',
      representativePhone: '+998 90 000 01 04',
      educationEngagement: 'PRESCHOOL',
    },
    signalSummary: 'Olti oylik reja muddati yakunlandi; rivojlanish natijalari va xizmat intensivligi ko‘rib chiqiladi.',
    needs: [
      { id: 'need-004-a', domain: 'COMMUNICATION', summary: 'Kommunikatsiya ko‘nikmalarini mustahkamlash', severity: 'MEDIUM', assessed: true },
      { id: 'need-004-b', domain: 'SELF_CARE', summary: 'Kundalik mustaqillik', severity: 'MEDIUM', assessed: true },
    ],
    consentStatus: 'RECORDED',
    assignedTeam: 'Mirzo Ulug‘bek tuman multidisiplinar jamoasi',
    owner: 'Sh. Mamatova',
    createdAt: '2026-02-14T10:00:00+05:00',
    updatedAt: '2026-08-28T12:00:00+05:00',
    dueAt: '2026-09-05',
    nextAction: 'Natijalar bo‘yicha oila ishtirokidagi review uchrashuvi',
    flags: { urgent: false, safeguarding: false, currentlyUnserved: false, overdue: false },
    plan: {
      id: 'plan-004',
      version: 1,
      status: 'REVISION_REQUIRED',
      goals: ['Ikki bosqichli ko‘rsatmani bajarish', 'Kundalik faoliyatda yordamni kamaytirish'],
      familyReviewedAt: '2026-02-16',
      approvedAt: '2026-02-18',
      reviewDate: '2026-08-28',
      owner: 'Sh. Mamatova',
      referrals: [
        { id: 'ref-004-a', serviceCode: 'S2', serviceName: 'Erta aralashuv mashg‘uloti', status: 'STARTED', providerName: 'Bolalar rivojlanish markazi', owner: 'Z. Safarova', requestedAt: '2026-02-18', actualStartDate: '2026-02-22', updatedAt: '2026-08-26T11:00:00+05:00' },
        { id: 'ref-004-b', serviceCode: 'S3', serviceName: 'Ergoterapiya', status: 'STARTED', providerName: 'Shahar reabilitatsiya markazi', owner: 'K. Ismoilov', requestedAt: '2026-02-18', actualStartDate: '2026-03-01', updatedAt: '2026-08-27T10:00:00+05:00' },
      ],
    },
    timeline: [
      { id: 'evt-004-a', at: '2026-08-14T08:00:00+05:00', kind: 'SYSTEM', title: 'Review muddati eslatildi', description: 'Case egasi va oilaga 14 kunlik eslatma yuborildi.', actor: 'PTPK tizimi' },
      { id: 'evt-004-b', at: '2026-08-28T12:00:00+05:00', kind: 'REVIEW', title: 'Natijalar jamlandi', description: 'Rejani yangilash uchun mutaxassis xulosalari tayyor.', actor: 'Sh. Mamatova' },
    ],
  },
  {
    id: 'case-005',
    displayId: 'PTPK-2026-00125',
    type: 'C5',
    intakeChannel: 'HEALTHCARE',
    priority: 'PRIORITY',
    phase: 'ASSESSMENT',
    child: {
      id: 'child-005',
      fullName: 'Sardor Raxmatov',
      birthDate: '2015-09-18',
      pinfl: '41509180000005',
      gender: 'MALE',
      district: 'Sergeli tumani',
      representativeName: 'Mavluda Raxmatova',
      representativePhone: '+998 90 000 01 05',
      educationEngagement: 'SCHOOL',
    },
    signalSummary: 'Operatsiyadan keyingi harakat cheklovi amaldagi ta’lim va ijtimoiy rejaning qayta baholanishini talab qildi.',
    needs: [
      { id: 'need-005-a', domain: 'HEALTH', summary: 'Operatsiyadan keyingi reabilitatsiya', severity: 'HIGH', assessed: true },
      { id: 'need-005-b', domain: 'MOBILITY', summary: 'Maktab muhitidagi vaqtinchalik moslashtirish', severity: 'HIGH', assessed: false },
    ],
    consentStatus: 'RECORDED',
    assignedTeam: 'Sergeli tuman multidisiplinar jamoasi',
    owner: 'F. Nazarov',
    createdAt: '2026-08-18T13:10:00+05:00',
    updatedAt: '2026-08-29T08:20:00+05:00',
    dueAt: '2026-08-30',
    nextAction: 'Harakatlanish baholashini va vaqtinchalik moslashtirishni kelishish',
    flags: { urgent: false, safeguarding: false, currentlyUnserved: false, overdue: false },
    plan: {
      id: 'plan-005',
      version: 3,
      status: 'REVISION_REQUIRED',
      goals: ['Ta’limdagi qatnashuvni saqlash', 'Tiklanish davrida xavfsiz harakatlanish'],
      reviewDate: '2026-09-15',
      owner: 'F. Nazarov',
      referrals: [
        { id: 'ref-005-a', serviceCode: 'S1', serviceName: 'Maktabdagi vaqtinchalik moslashtirish', status: 'STARTED', providerName: '300-sonli maktab', owner: 'B. Qosimova', requestedAt: '2026-08-19', actualStartDate: '2026-08-20', updatedAt: '2026-08-28T15:30:00+05:00' },
        { id: 'ref-005-b', serviceCode: 'S3', serviceName: 'Operatsiyadan keyingi reabilitatsiya', status: 'READY_TO_REFER', owner: 'R. Xolmatov', requestedAt: '2026-08-28', targetStartDate: '2026-09-01', updatedAt: '2026-08-29T08:20:00+05:00' },
        { id: 'ref-005-c', serviceCode: 'S4', serviceName: 'Uyda qisqa muddatli ijtimoiy yordam', status: 'STARTED', providerName: 'Inson markazi', owner: 'D. Nasriddinova', requestedAt: '2026-08-19', actualStartDate: '2026-08-21', updatedAt: '2026-08-28T12:10:00+05:00' },
      ],
    },
    timeline: [
      { id: 'evt-005-a', at: '2026-08-18T13:10:00+05:00', kind: 'SIGNAL', title: 'Sog‘liqdagi o‘zgarish qayd etildi', description: 'C5 case mavjud reja bilan bog‘landi.', actor: 'Sog‘liqni saqlash integratsiyasi' },
      { id: 'evt-005-b', at: '2026-08-20T09:00:00+05:00', kind: 'SERVICE', title: 'Ta’lim moslashtirildi', description: 'Amaldagi ta’lim xizmati uzilmadi.', actor: '300-sonli maktab' },
    ],
  },
  {
    id: 'case-006',
    displayId: 'PTPK-2026-00118',
    type: 'C6',
    intakeChannel: 'EDUCATION',
    priority: 'ROUTINE',
    phase: 'AUTHORIZATION',
    child: {
      id: 'child-006',
      fullName: 'Aziza Yoqubova',
      birthDate: '2019-01-12',
      pinfl: '61901120000006',
      gender: 'FEMALE',
      district: 'Yashnobod tumani',
      representativeName: 'Ozoda Yoqubova',
      representativePhone: '+998 90 000 01 06',
      educationEngagement: 'PRESCHOOL',
    },
    signalSummary: 'Bog‘chadan maktabga o‘tish uchun ta’lim, rivojlantirish va transport xizmatlari uzluksizligi rejalashtirilmoqda.',
    needs: [
      { id: 'need-006-a', domain: 'LEARNING', summary: 'Maktabga yumshoq o‘tish va resurs yordam', severity: 'MEDIUM', assessed: true },
      { id: 'need-006-b', domain: 'FAMILY_ACCESS', summary: 'Transport va oilaga yo‘riqnoma', severity: 'MEDIUM', assessed: true },
    ],
    consentStatus: 'RECORDED',
    assignedTeam: 'Yashnobod tuman multidisiplinar jamoasi',
    owner: 'S. Gʻaniyeva',
    createdAt: '2026-08-10T09:30:00+05:00',
    updatedAt: '2026-08-28T16:45:00+05:00',
    dueAt: '2026-09-01',
    nextAction: 'O‘tish davri integratsiyalashgan paketini tasdiqlash',
    flags: { urgent: false, safeguarding: false, currentlyUnserved: false, overdue: false },
    plan: {
      id: 'plan-006',
      version: 1,
      status: 'APPROVAL_PENDING',
      goals: ['Birinchi o‘quv kunidan xizmatlarni uzluksiz davom ettirish', 'Oilaga yagona aloqa nuqtasini taqdim etish'],
      familyReviewedAt: '2026-08-27',
      reviewDate: '2026-10-15',
      owner: 'S. Gʻaniyeva',
      referrals: [
        { id: 'ref-006-a', serviceCode: 'S1', serviceName: 'Maktab va resurs pedagog', status: 'SCHEDULED', providerName: '149-sonli maktab', owner: 'M. Soliyeva', requestedAt: '2026-08-12', targetStartDate: '2026-09-02', updatedAt: '2026-08-28T11:00:00+05:00' },
        { id: 'ref-006-b', serviceCode: 'S2', serviceName: 'O‘tish davrida rivojlantiruvchi mashg‘ulot', status: 'STARTED', providerName: 'Erta aralashuv markazi', owner: 'N. Salimova', requestedAt: '2026-08-12', actualStartDate: '2026-08-15', updatedAt: '2026-08-27T10:00:00+05:00' },
        { id: 'ref-006-c', serviceCode: 'S5', serviceName: 'Maktab transportiga kirish', status: 'REFERRED', owner: 'D. Saidov', requestedAt: '2026-08-20', targetStartDate: '2026-09-02', updatedAt: '2026-08-28T16:45:00+05:00' },
        { id: 'ref-006-d', serviceCode: 'S6', serviceName: 'O‘tish davri integratsiyalashgan paketi', status: 'READY_TO_REFER', owner: 'S. Gʻaniyeva', requestedAt: '2026-08-28', targetStartDate: '2026-09-02', updatedAt: '2026-08-28T16:45:00+05:00' },
      ],
    },
    timeline: [
      { id: 'evt-006-a', at: '2026-08-10T09:30:00+05:00', kind: 'SIGNAL', title: 'O‘tish case’i ochildi', description: 'Bog‘cha va maktab ma’lumotlari yagona profilga bog‘landi.', actor: 'Ta’lim integratsiyasi' },
      { id: 'evt-006-b', at: '2026-08-27T15:00:00+05:00', kind: 'PLAN', title: 'Oila rejani ko‘rib chiqdi', description: 'Transport va yagona case-manager talabi qo‘shildi.', actor: 'S. Gʻaniyeva' },
    ],
  },
  {
    id: 'case-007',
    displayId: 'PTPK-2026-00145',
    type: 'C7',
    intakeChannel: 'CHILD_PROTECTION',
    priority: 'URGENT',
    phase: 'SERVICE_COORDINATION',
    child: {
      id: 'child-007',
      fullName: 'Jasmina Nabiyeva',
      birthDate: '2017-05-22',
      pinfl: '41705220000007',
      gender: 'FEMALE',
      district: 'Shayxontohur tumani',
      representativeName: 'Saida Nabiyeva',
      representativePhone: '+998 90 000 01 07',
      educationEngagement: 'SCHOOL',
    },
    signalSummary: 'Xavfsizlik riski va zudlik bilan tibbiy ko‘rik talab qiluvchi shoshilinch himoya signali.',
    needs: [
      { id: 'need-007-a', domain: 'SAFETY', summary: 'Darhol xavfsiz muhit va himoya rejasi', severity: 'CRITICAL', assessed: true },
      { id: 'need-007-b', domain: 'HEALTH', summary: 'Shoshilinch tibbiy ko‘rik', severity: 'HIGH', assessed: true },
    ],
    consentStatus: 'LEGAL_BASIS_RECORDED',
    assignedTeam: 'Shahar shoshilinch multidisiplinar jamoasi',
    owner: 'Z. Usmonova',
    createdAt: '2026-08-29T07:35:00+05:00',
    updatedAt: '2026-08-29T11:25:00+05:00',
    dueAt: '2026-08-29',
    nextAction: 'Doimiy himoya variantini vakolatli mutaxassis bilan tasdiqlash',
    flags: { urgent: true, safeguarding: true, currentlyUnserved: false, overdue: false },
    plan: {
      id: 'plan-007',
      version: 1,
      status: 'APPROVED',
      goals: ['Bolaning zudlik bilan xavfsizligini ta’minlash', 'Ta’limni imkon qadar uzmaslik'],
      approvedAt: '2026-08-29',
      reviewDate: '2026-09-01',
      owner: 'Z. Usmonova',
      referrals: [
        { id: 'ref-007-a', serviceCode: 'S3', serviceName: 'Shoshilinch tibbiy ko‘rik', status: 'SCHEDULED', providerName: 'Bolalar shoshilinch markazi', owner: 'U. Kamilov', requestedAt: '2026-08-29', targetStartDate: '2026-08-29', isTemporary: true, updatedAt: '2026-08-29T08:05:00+05:00' },
        { id: 'ref-007-b', serviceCode: 'S4', serviceName: 'Vaqtinchalik ijtimoiy parvarish', status: 'PROVIDER_ACCEPTED', providerName: 'Shahar ijtimoiy xizmat markazi', owner: 'M. Raximova', requestedAt: '2026-08-29', targetStartDate: '2026-08-29', isTemporary: true, updatedAt: '2026-08-29T09:10:00+05:00' },
        { id: 'ref-007-c', serviceCode: 'S5', serviceName: 'Shoshilinch himoya va oila bilan ishlash', status: 'STARTED', providerName: 'Bola himoyasi xizmati', owner: 'Z. Usmonova', requestedAt: '2026-08-29', actualStartDate: '2026-08-29', isTemporary: true, updatedAt: '2026-08-29T11:25:00+05:00' },
      ],
    },
    timeline: [
      { id: 'evt-007-a', at: '2026-08-29T07:35:00+05:00', kind: 'SIGNAL', title: 'Shoshilinch signal qabul qilindi', description: 'SLA va navbatchi jamoa avtomatik faollashtirildi.', actor: 'Bola himoyasi kanali' },
      { id: 'evt-007-b', at: '2026-08-29T08:05:00+05:00', kind: 'SERVICE', title: 'Vaqtinchalik xizmatlar ishga tushirildi', description: 'To‘liq baholashni kutmasdan xavfsiz vaqtinchalik yo‘l tanlandi.', actor: 'Z. Usmonova' },
    ],
  },
  {
    id: 'case-008',
    displayId: 'PTPK-2026-00102',
    type: 'C8',
    intakeChannel: 'PROVIDER',
    priority: 'PRIORITY',
    phase: 'MONITORING',
    child: {
      id: 'child-008',
      fullName: 'Bobur Erkinov',
      birthDate: '2013-12-08',
      pinfl: '41312080000008',
      gender: 'MALE',
      district: 'Uchtepa tumani',
      representativeName: 'Nigora Erkinova',
      representativePhone: '+998 90 000 01 08',
      educationEngagement: 'SCHOOL',
    },
    signalSummary: 'Reabilitatsiya xizmati tasdiqlangan, ammo provayder quvvati yo‘qligi sabab 31 kundan beri boshlanmagan.',
    needs: [
      { id: 'need-008-a', domain: 'MOBILITY', summary: 'Tasdiqlangan reabilitatsiya kursini boshlash', severity: 'HIGH', assessed: true },
      { id: 'need-008-b', domain: 'FAMILY_ACCESS', summary: 'Provayderga transport', severity: 'MEDIUM', assessed: true },
    ],
    consentStatus: 'RECORDED',
    assignedTeam: 'Uchtepa tuman multidisiplinar jamoasi',
    owner: 'A. Mirzayev',
    createdAt: '2026-07-26T10:20:00+05:00',
    updatedAt: '2026-08-29T10:05:00+05:00',
    dueAt: '2026-08-20',
    nextAction: 'Muqobil provayder bo‘yicha tumanlararo eskalatsiyani yakunlash',
    flags: { urgent: false, safeguarding: false, currentlyUnserved: false, overdue: true },
    plan: {
      id: 'plan-008',
      version: 1,
      status: 'ACTIVE',
      goals: ['Reabilitatsiyani 10 ish kuni ichida boshlash', 'Kirish to‘siqlarini bartaraf etish'],
      familyReviewedAt: '2026-07-27',
      approvedAt: '2026-07-28',
      reviewDate: '2026-09-10',
      owner: 'A. Mirzayev',
      referrals: [
        { id: 'ref-008-a', serviceCode: 'S3', serviceName: 'Harakat reabilitatsiyasi', status: 'WAITLISTED', providerName: 'Uchtepa reabilitatsiya bo‘limi', owner: 'T. Egamberdiyev', requestedAt: '2026-07-28', targetStartDate: '2026-08-05', waitingDays: 31, capacityNote: 'Mahalliy quvvat yo‘q; shahar bo‘yicha muqobil qidirilmoqda', updatedAt: '2026-08-29T10:05:00+05:00' },
        { id: 'ref-008-b', serviceCode: 'S5', serviceName: 'Xizmatga transport', status: 'STARTED', providerName: 'Tuman transport xizmati', owner: 'J. Eshonqulov', requestedAt: '2026-07-28', actualStartDate: '2026-08-01', updatedAt: '2026-08-28T09:00:00+05:00' },
      ],
    },
    timeline: [
      { id: 'evt-008-a', at: '2026-08-08T08:00:00+05:00', kind: 'SYSTEM', title: 'C8 signali yaratildi', description: 'Tasdiqlangan xizmat target sanadan uch kun o‘tib ham boshlanmadi.', actor: 'PTPK tizimi' },
      { id: 'evt-008-b', at: '2026-08-29T10:05:00+05:00', kind: 'REFERRAL', title: 'Shahar darajasiga eskalatsiya qilindi', description: 'Ehtiyoj va yo‘llanma faol holatda saqlandi.', actor: 'A. Mirzayev' },
    ],
  },
  {
    id: 'case-009',
    displayId: 'PTPK-2026-00097',
    type: 'C9',
    intakeChannel: 'FAMILY',
    priority: 'PRIORITY',
    phase: 'REVIEW',
    child: {
      id: 'child-009',
      fullName: 'Temurbek Alimov',
      birthDate: '2012-06-14',
      pinfl: '41206140000009',
      gender: 'MALE',
      district: 'Bektemir tumani',
      representativeName: 'Maftuna Alimova',
      representativePhone: '+998 90 000 01 09',
      educationEngagement: 'SCHOOL',
    },
    signalSummary: 'Oila reabilitatsiya intensivligi bo‘yicha qarorni qayta ko‘rib chiqishni so‘radi.',
    needs: [
      { id: 'need-009-a', domain: 'HEALTH', summary: 'Reabilitatsiya intensivligini qayta baholash', severity: 'HIGH', assessed: true },
      { id: 'need-009-b', domain: 'LEARNING', summary: 'Amaldagi ta’limni uzluksiz davom ettirish', severity: 'MEDIUM', assessed: true },
    ],
    consentStatus: 'RECORDED',
    assignedTeam: 'Shahar mustaqil review guruhi',
    owner: 'D. Abduqodirova',
    createdAt: '2026-08-15T14:30:00+05:00',
    updatedAt: '2026-08-29T09:15:00+05:00',
    dueAt: '2026-09-06',
    nextAction: 'Mustaqil ekspert xulosasini apellyatsiya materialiga qo‘shish',
    flags: { urgent: false, safeguarding: false, currentlyUnserved: false, overdue: false },
    plan: {
      id: 'plan-009',
      version: 2,
      status: 'ACTIVE',
      goals: ['Amaldagi ta’limni davom ettirish', 'Funktsional ehtiyojga mos reabilitatsiya olish'],
      familyReviewedAt: '2026-08-16',
      approvedAt: '2026-08-17',
      reviewDate: '2026-09-06',
      owner: 'D. Abduqodirova',
      referrals: [
        { id: 'ref-009-a', serviceCode: 'S1', serviceName: 'Inklyuziv ta’lim', status: 'STARTED', providerName: '290-sonli maktab', owner: 'H. Sodiqova', requestedAt: '2026-01-10', actualStartDate: '2026-01-15', updatedAt: '2026-08-28T14:00:00+05:00' },
        { id: 'ref-009-b', serviceCode: 'S3', serviceName: 'Intensiv reabilitatsiya', status: 'WAITLISTED', providerName: 'Shahar reabilitatsiya markazi', owner: 'R. Mahmudov', requestedAt: '2026-08-17', targetStartDate: '2026-09-10', waitingDays: 12, capacityNote: 'Apellyatsiya ko‘rib chiqilayotgan bo‘lsa ham navbat saqlanadi', updatedAt: '2026-08-29T09:15:00+05:00' },
        { id: 'ref-009-c', serviceCode: 'S5', serviceName: 'Xizmatga moslashtirilgan transport', status: 'MATCHING', owner: 'M. Xudoyberdiyev', requestedAt: '2026-08-24', targetStartDate: '2026-09-05', capacityNote: 'Hudud va jadval bo‘yicha mos tashuvchi qidirilmoqda', updatedAt: '2026-08-29T09:00:00+05:00' },
      ],
    },
    appeal: {
      id: 'appeal-009',
      status: 'UNDER_REVIEW',
      subject: 'Reabilitatsiya mashg‘ulotlari intensivligini oshirish',
      submittedAt: '2026-08-22',
      owner: 'I. Sobirov',
      dueAt: '2026-09-06',
      existingServicesContinue: true,
    },
    timeline: [
      { id: 'evt-009-a', at: '2026-08-22T10:30:00+05:00', kind: 'APPEAL', title: 'Apellyatsiya ro‘yxatga olindi', description: 'Alohida review oqimi ochildi, amaldagi xizmatlar davom etmoqda.', actor: 'D. Abduqodirova' },
      { id: 'evt-009-b', at: '2026-08-29T09:15:00+05:00', kind: 'APPEAL', title: 'Mustaqil ekspert tayinlandi', description: 'Qarorda qatnashmagan ekspertga materiallar yuborildi.', actor: 'I. Sobirov' },
    ],
  },
  {
    id: 'case-010',
    displayId: 'PTPK-2026-00139',
    type: 'C1',
    intakeChannel: 'MAHALLA',
    priority: 'ROUTINE',
    phase: 'MONITORING',
    child: {
      id: 'child-010',
      fullName: 'Sevinch Murodova',
      birthDate: '2018-10-27',
      pinfl: '41810270000010',
      gender: 'FEMALE',
      district: 'Yangihayot tumani',
      representativeName: 'Zarnigor Murodova',
      representativePhone: '+998 90 000 01 10',
      educationEngagement: 'SCHOOL',
    },
    signalSummary: 'Mahalla aniqlagan yengil kirish to‘sig‘i bazaviy yordam bilan hal qilinmoqda; maxsus xizmat shart emas.',
    needs: [
      { id: 'need-010-a', domain: 'FAMILY_ACCESS', summary: 'Oila uchun xizmatlar bo‘yicha navigatsiya', severity: 'LOW', assessed: true },
    ],
    consentStatus: 'RECORDED',
    assignedTeam: 'Yangihayot hududiy case jamoasi',
    owner: 'N. Ashurova',
    createdAt: '2026-08-24T16:00:00+05:00',
    updatedAt: '2026-08-29T10:30:00+05:00',
    dueAt: '2026-09-20',
    nextAction: 'Bazaviy yordam natijasini 30 kundan keyin tekshirish',
    flags: { urgent: false, safeguarding: false, currentlyUnserved: false, overdue: false },
    plan: {
      id: 'plan-010',
      version: 1,
      status: 'ACTIVE',
      goals: ['Oilani mavjud universal xizmatlar bilan bog‘lash', 'Yangi ehtiyoj paydo bo‘lsa erta signal olish'],
      familyReviewedAt: '2026-08-25',
      approvedAt: '2026-08-25',
      reviewDate: '2026-09-20',
      owner: 'N. Ashurova',
      referrals: [
        { id: 'ref-010-a', serviceCode: 'S0', serviceName: 'Ota-onaga navigatsiya va 30 kunlik monitoring', status: 'STARTED', providerName: 'Yangihayot Inson markazi', owner: 'N. Ashurova', requestedAt: '2026-08-25', actualStartDate: '2026-08-26', updatedAt: '2026-08-29T10:30:00+05:00' },
      ],
    },
    timeline: [
      { id: 'evt-010-a', at: '2026-08-24T16:00:00+05:00', kind: 'SIGNAL', title: 'Mahalla signali qabul qilindi', description: 'Triage maxsus baholashsiz bazaviy yordamni tavsiya qildi.', actor: 'Mahalla kanali' },
      { id: 'evt-010-b', at: '2026-08-26T11:00:00+05:00', kind: 'SERVICE', title: 'Bazaviy yordam boshlandi', description: 'Case monitoring holatiga o‘tkazildi.', actor: 'N. Ashurova' },
    ],
  },
]

export function getPtpkCaseTypeDefinition(code: PTPKCase['type']) {
  return ptpkCaseTypeDefinitions.find((item) => item.code === code)
}

export function getPtpkServiceRouteDefinition(code: PTPKServiceRouteDefinition['code']) {
  return ptpkServiceRouteDefinitions.find((item) => item.code === code)
}

// Short aliases are the stable UI-facing exports used by the PTPK pages.
export const caseTypeDefinitions = ptpkCaseTypeDefinitions
export const serviceRouteDefinitions = ptpkServiceRouteDefinitions
export const intakeChannelDefinitions = ptpkIntakeChannelDefinitions
export const casePhaseDefinitions = ptpkCasePhaseDefinitions
export const planStatusDefinitions = ptpkPlanStatusDefinitions
export const referralStatusDefinitions = ptpkReferralStatusDefinitions
export const appealStatusDefinitions = ptpkAppealStatusDefinitions
export const processSteps = ptpkProcessSteps
export const demoCases = ptpkDemoCases
